### PR TITLE
Update list streams component for new endpoint

### PR DESCRIPTION
**Pull request by jenessaman**
@psarras - as discussed, a get streams endpoint intended for clients has been added to the api

### CODE REVIEW

**Comment by psarras** [comment]
@jenessaman there are compile errors so lets hold on for a second. 😄 
I think in order to incorporate this, we would  have to add the new nuget packages. I would have a quick look and push the changes here!

**Comment by psarras** [comment]
@jenessaman I cannot find the new API, on the SpeckCxCore! Is it part of the new nuget?

**Review by psarras — APPROVED** [review]
Hey @jenessaman I've added the new Nuget + brought in the changes from the current ```master``` that you published and did a quick test. All seems to work as expected now. I will leave it open today so you can have a quick look and then we can merge it! Cheers.

**Comment by jenessaman** [comment]
Awesome, thanks @psarras! Do you want to include test gh files or shall we remove them?

**Comment by psarras** [comment]
@jenessaman let's keep them I want to reference them on the documentation on the website as well! Cheers

**Pull request merged**
